fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    nodejs: 'https://github.com/voxpupuli/puppet-nodejs.git'
  forge_modules:
    supervisor: 'proletaryo-supervisor'
  symlinks:
    ghost: "#{source_dir}"
