fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    nodejs:
      repo: 'https://github.com/puppetlabs/puppetlabs-nodejs.git'
  forge_modules:
    supervisor: "proletaryo-supervisor"
  symlinks:
    ghost: "#{source_dir}"
